services:
  db:
    container_name: changelog-generator
    image: postgres:latest
    environment:
      POSTGRES_DB: changelog-generator
      POSTGRES_USER: manjama
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5323:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
